
CREATE TABLE F_USER_MSG_POINT
(
   OS_ID                VARCHAR2(20) NOT NULL,
   USER_CODE            VARCHAR2(32) NOT NULL,
   USER_NAME            VARCHAR2(50),
   DEVICE_TYPE          CHAR ,
   DEVICE_ID            VARCHAR2(100),
   OS_VERSION           VARCHAR2(100),
   CHANNEL_ID           VARCHAR2(100),
   WX_TOKEN             VARCHAR2(100) ,
   MOBILE_PHONE         VARCHAR2(13) ,
   EMAIL_ADDRESS        VARCHAR2(100),
   PRIMARY KEY (USER_CODE, OS_ID)
);
COMMENT ON TABLE F_USER_MSG_POINT IS '用户设置 自己接收 通知的方式。';
COMMENT ON COLUMN F_USER_MSG_POINT.DEVICE_TYPE IS '3 ：android ； 4：apple ， 0： 没有';
COMMENT ON COLUMN F_USER_MSG_POINT.WX_TOKEN IS '公众号下的令牌';
COMMENT ON COLUMN F_USER_MSG_POINT.MOBILE_PHONE IS '用于短信';


CREATE TABLE F_MESSAGE_DELIVERY
(
   MSG_ID               VARCHAR2(32) NOT NULL,
   MSG_SENDER           VARCHAR2(100),
   PUSH_TYPE            CHAR(1) ,
   MSG_RECEIVER         VARCHAR2(100) NOT NULL,
   MSG_TYPE             VARCHAR2(32) ,
   MSG_SUBJECT          VARCHAR2(100),
   MSG_CONTENT          VARCHAR2(1000) NOT NULL,
   REL_URL              VARCHAR2(500),
   NOTICE_TYPES         VARCHAR2(100) ,
   PUSH_STATE           CHAR(1) ,
   PUSH_RESULT          VARCHAR2(500) ,
   PLAN_PUSH_TIME       DATE,
   PUSH_TIME            DATE,
   VALID_PERIOD         DATE,
   OS_ID                VARCHAR2(20),
   OPT_ID               VARCHAR2(64) NOT NULL  ,
   OPT_METHOD           VARCHAR2(64)  ,
   OPT_TAG              VARCHAR2(200) ,
   PRIMARY KEY (MSG_ID)
);
COMMENT ON COLUMN F_MESSAGE_DELIVERY.PUSH_TYPE IS '点对点、群发';
COMMENT ON COLUMN F_MESSAGE_DELIVERY.MSG_TYPE IS '客户端用来解析';
COMMENT ON COLUMN F_MESSAGE_DELIVERY.NOTICE_TYPES IS '可以多种方式  A：app推送， S：短信  C：微信  N：内部通知系统';
COMMENT ON COLUMN F_MESSAGE_DELIVERY.PUSH_STATE IS '0 成功， 1 失败 2 部分成功';
COMMENT ON COLUMN F_MESSAGE_DELIVERY.PUSH_RESULT IS '成功为 第三方 msgid 失败为 失败原因';
COMMENT ON COLUMN F_MESSAGE_DELIVERY.OPT_ID IS '模块，或者表';
COMMENT ON COLUMN F_MESSAGE_DELIVERY.OPT_METHOD IS '方法，或者字段';
COMMENT ON COLUMN F_MESSAGE_DELIVERY.OPT_TAG IS '一般用于关联到业务主体';

CREATE TABLE F_USER_NOTIFY_SETTING
(
   USER_SETTING_ID      VARCHAR2(32) NOT NULL,
   USER_CODE            VARCHAR2(32),
   OS_ID                VARCHAR2(20)  ,
   OPT_ID               VARCHAR2(64) NOT NULL ,
   NOTIFY_TYPES         VARCHAR2(100) ,
   PRIMARY KEY (USER_SETTING_ID)
);
COMMENT ON TABLE F_USER_NOTIFY_SETTING IS '用户设置 自己接收 通知的方式。';
COMMENT ON COLUMN F_USER_NOTIFY_SETTING.OS_ID IS  '"Default" 表示所有系统的默认值';
COMMENT ON COLUMN F_USER_NOTIFY_SETTING.OPT_ID IS  '"Default" 表示所有系统的默认值模块';
COMMENT ON COLUMN F_USER_NOTIFY_SETTING.NOTIFY_TYPES IS  '接收通知的方式，可以有多种方式';
